### ISSUE TITLE
How to install different wine version i need wine 9.0 

### ISSUE THREAD

**Issue by KintCark** [AllPlatform/Fex-Android#1]
Does your fex have an terminal mode I want to install different wine
7.0 sucks

**Comment by GuilhermeDunkly** [comment]
Ah cara, talvez ele adicione a capacidade de trocar de wine nas proximas atualizações (use the translator)

**Comment by AllPlatform** [comment]
fex is not supported from wine 8.19 onwards

**Comment by GuilhermeDunkly** [comment]
Why?

**Comment by AllPlatform** [comment]
Create issuse here [FEX-EMU](https://github.com/FEX-Emu/FEX)
