### ISSUE TITLE
InputBridge not working with WineEsync

### ISSUE THREAD

**Issue by Kryon475** [AllPlatform/Fex-Android#11]
Hello, when I start InputBridge with WineEsync enabled, it crashes. Is it possible to fix this? In the game I need it greatly increases performance. I use wine-ge 8.15, and chroot mode
Old versions IB also not work

https://github.com/AllPlatform/Fex-Android/assets/105074128/202fe1a3-8b3a-4263-8610-62d06245c750

**Comment by AllPlatform** [comment]
it seems the i386 library in rootfs is missing pls wait

**Comment by AllPlatform** [comment]
![Screenshot_2024-01-10-12-04-50-362_com termux x11](https://github.com/AllPlatform/Fex-Android/assets/44525248/6f834233-2eb1-4738-8c65-e4095acbac61)
strangely it all works for me

**Comment by AllPlatform** [comment]
In chroot mode something is wrong, I will check the rootfs again, please do not grant root permission to termux to automatically switch to proot mode or you can turn on debug to move to proot mode
Winesync will work on proot mode

**Comment by Kryon475** [comment]
I tried it, IB with esync crashes in proot too

**Comment by AllPlatform** [comment]
strangely it works for me in proot mode
![Screenshot_2024-01-10-12-04-50-362_com termux x11](https://github.com/AllPlatform/Fex-Android/assets/44525248/683ca4c0-d673-4883-9d50-b009f979d616)

**Comment by Kryon475** [comment]
You use IB 0.1.8? In my case, with this version and older, the application itself does not crash, but the gear does not appear when opening the Android IB application

Its log from debug mode 
[log.txt](https://github.com/AllPlatform/Fex-Android/files/13884305/log.txt)

**Comment by AllPlatform** [comment]
Can you try version 0.1.9.9? It works for me
![Screenshot_2024-01-10-17-19-09-847_com catfixture inputbridge](https://github.com/AllPlatform/Fex-Android/assets/44525248/05c57868-4b42-4689-afee-75887374d5b4)

**Comment by Kryon475** [comment]
0.1.9.9 also not work (ib.exe crashes). On 0.1.8 and older ib.exe not crashing, but gear for open my IB profile not appear

**Comment by AllPlatform** [comment]
Try remove all `export FEX_X87REDUCEDPRECISION=true` in `/data/data/com.termux/files/usr/bin/fex`
![Screenshot_2024-01-10-18-17-49-427_com termux](https://github.com/AllPlatform/Fex-Android/assets/44525248/1c35fdd1-77a1-4194-9100-a4dc3cee3c96)

**Comment by Kryon475** [comment]
Unfortunately, it didn't help :(

**Comment by AllPlatform** [comment]
I haven't thought of a solution yet

**Comment by Kryon475** [comment]
Maybe it problem with my firmware( On another phone IB working even on chroot

UPD: I tested new 1.4 version and IB now working on my phone. Thanks!
