### ISSUE TITLE
Please add vk3d 2.11 i need this please!!!!

### ISSUE THREAD

**Issue by KintCark** [AllPlatform/Fex-Android#2]
Evey game I've tried works but there's one game I'm trying that needs vk3d 2.11 I tried putting it inside the c drive manually but fex emu not detecting it. I put vk3d in the game folder but it crashes I think it crash because it's trying to load dxvk and vk3d a y the same time please update fex endroid and add vk3d 2.11ci need it for dx12 games pleaassee!! We need an update.

**Comment by AllPlatform** [comment]
i think you forgot to register the library for d3d12
Just `start>run>winecfg` click to library tab
add `d3d12` > `apply` > `ok`
Don't forget copy d3d12 to system32

**Comment by KintCark** [comment]
I did but it still doesn't work

**Comment by KintCark** [comment]
U forgot d3d12core.dll but it's not working

**Comment by AllPlatform** [comment]
I will design an update to see the debug log please wait

**Comment by AllPlatform** [comment]
Vk3d-proton is add
