### ISSUE TITLE
Please add gpl-async 2.1-2.3

### ISSUE THREAD

**Issue by KintCark** [AllPlatform/Fex-Android#3]
Hey I noticed u didn't add gplasync dxvks I'm trying to play a game but it doesn't work with any of the current dxvk so I need dxvk gpl async thanks:)

**Comment by AllPlatform** [comment]
Oh ok

**Comment by AllPlatform** [comment]
If the game you try doesn't work with any dxvk then you better enable debugging then send me the log
`Configure Fex` > `DEBUG   Run Fex-emu with Wine Debug in proot` > `Enabled` 
`Start Fex-Emu` run your game

**Comment by KintCark** [comment]
I'm sorry the game works its was because the steam game I downloaded had a
virus. I no longer gonna download steam games from internet they have
viruses. The game works now

**Comment by AllPlatform** [comment]
gpl-async is add
