### ISSUE TITLE
Arman harie

### ISSUE THREAD

**Issue by 2R3J** [AllPlatform/Fex-Android#5]
Please fix black screen Mr... In my phone windows not booting...

**Comment by AllPlatform** [comment]
@2R3J sent me debug log in 
`Configure fex`>`debug`>`Enabled`

**Comment by 2R3J** [comment]
preloader: Warning: failed to reserve range 00007ffffe000000-00007fffffff0000
preloader: Warning: failed to reserve range 00007ffffe000000-00007fffffff0000
002c:err:winediag:getaddrinfo Failed to resolve your host name IP
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
preloader: Warning: failed to reserve range 00007ffffe000000-00007fffffff0000
preloader: Warning: failed to reserve range 00007ffffe000000-00007fffffff0000
preloader: Warning: failed to reserve range 00007ffffe000000-00007fffffff0000
006c:err:wineusb:DriverEntry Failed to initialize Unix library, status 0xc0000135.
006c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000135
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 126
preloader: Warning: failed to reserve range 00007ffffe000000-00007fffffff0000
0094:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
preloader: Warning: failed to reserve range 00007ffffe000000-00007fffffff0000
0094:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0094:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0094:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
preloader: Warning: failed to reserve range 00007ffffe000000-00007fffffff0000
00d8:err:nsi:poll_netlink bind failed, errno 13.
preloader: Warning: failed to reserve range 00007ffffe000000-00007fffffff0000
preloader: Warning: failed to reserve range 00007ffffe000000-00007fffffff0000
XSetIMValues
destroyCallback
RV: (nil)
XGetIMValues
0x750fa672c8
0x1000ff708
RV: (nil)
XSetIMValues
destroyCallback
RV: (nil)
XGetIMValues
0x750fa672c8
0x1001fdda8
RV: (nil)

**Comment by AllPlatform** [comment]
There is no error. you have not waited long enough for fex to boot wine, fex is quite slow

**Comment by 2R3J** [comment]
Oh ...ok ..i am sorry...
