### ISSUE TITLE
Wine Debugger Error

### ISSUE THREAD

**Issue by hrachkovinovoto** [AllPlatform/Fex-Android#6]
Device: Snapdragon 870 
Even games from the early 2000s, like Diablo II, give this error:
![wTB7LMJ](https://github.com/AllPlatform/Fex-Android/assets/101092444/6f424849-7305-4581-8a4f-a0ba632f5c8d)

**Comment by hrachkovinovoto** [comment]
[debug870.txt](https://github.com/AllPlatform/Fex-Android/files/13707236/debug870.txt)

**Comment by AllPlatform** [comment]
fex only supports 64bit games, 32bit games are not supported
