### ISSUE TITLE
dpkg is corrupted 

### ISSUE THREAD

**Issue by 23xvx** [AllPlatform/Fex-Android#8]
![Screenshot_20231225_162942_Termux](https://github.com/AllPlatform/Fex-Android/assets/120558411/7051491c-d43f-429e-a744-2044987e003c)
I entered terminal mode and try to update packages.
It shows dpkg cant create backup file.

**Comment by AllPlatform** [comment]
I will fix it later

**Comment by 23xvx** [comment]
I have met this problem before.
Sometimes it happened when you change the name of the rootfs directory 
Like ubuntu-fs --> ubuntu64-fs
