### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by PhantasmProject** [AllPlatform/Fex-Android#9]
![Screenshot_20231228-130236_Termux_X11](https://github.com/AllPlatform/Fex-Android/assets/153091948/2422241c-f93a-41f3-a776-c63a6a00b1c1)

Hi, And that's it. Pixel 3xl 4/64 Android 13 doesn't display the desktop.

**Comment by AllPlatform** [comment]
#5

**Comment by PhantasmProject** [comment]
> [#5 ](https://github.com/AllPlatform/Fex-Android/issues/5)

Ok,sorry.)wait.
